name: MLOps Pipeline

on:
  push:
    branches:
      - walid
  pull_request:
    branches:
      - walid

jobs:
  pipeline:
    runs-on: ubuntu-latest  # or another OS if needed, e.g., 'windows-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt for dependencies

    - name: Run data pipeline
      run: |
        python pipeline1/your_script.py  # Adjust the path to where your script is located
      env:
        # If needed, add any environment variables here, e.g. MLflow tracking URI, etc.
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    - name: Commit trained model (Optional)
      run: |
        git add model.h5
        git commit -m "Add trained model"
        git push

