name: MLOps Pipeline

on:
  push:
    branches:
      - walid
  pull_request:
    branches:
      - walid

jobs:
  pipeline:
    runs-on: ubuntu-latest  # or another OS if needed, e.g., 'windows-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # specify the Python version you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies

    - name: Set the dataset directory environment variable
      run: echo "DATASET_DIR=${{ secrets.DATASET_DIR }}" >> $GITHUB_ENV

    - name: Run pipeline
      run: python pipeline1/run_pipeline.py  # Adjust the path to your script
      env:
        DATASET_DIR: ${{ secrets.DATASET_DIR }}  # Use the secret here

